blog/models.py
from exts import db
from datetime import datetime

class User(db.Model):
    __tablename__ = "user"
    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    telephone = db.Column(db.String(11))
    username = db.Column(db.String(100))
    password = db.Column(db.String(100))

class Question(db.Model):
    __tablename__ = 'question'
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(100))
    content = db.Column(db.Text)
    create_time = db.Column(db.DateTime,default=datetime.now)

    author_id = db.Column(db.Integer,db.ForeignKey('user.id'))

    author = db.relationship('User',backref='questions')

class Answer(db.Model):
    __tablename__ = 'answer'
    id = db.Column(db.Integer,primary_key=True)
    content = db.Column(db.Text)
    create_time = db.Column(db.DateTime, default=datetime.now)

    question_id = db.Column(db.Integer,db.ForeignKey('question.id'))
    author_id = db.Column(db.Integer,db.ForeignKey('user.id'))

    question = db.relationship('Question',backref=db.backref('answers',order_by = create_time.desc()))

    author = db.relationship('User',backref='answers')

blog/issue/views.py
from flask import Blueprint,render_template,request,redirect,url_for,session
from flask.views import MethodView
from exts import db
from models import User,Question,Answer
from decorators import login_required

issues = Blueprint('issues',__name__)

class Questions(MethodView):
    @login_required
    def get(self):
        return render_template('question.html')

    def post(self):
        title = request.form.get('title')
        content = request.form.get('content')
        question = Question(title=title,content=content)

        question.author_id = session.get('user_id')

        db.session.add(question)
        db.session.commit()
        return redirect(url_for('index'))

issues.add_url_rule('/question/',view_func=Questions.as_view('question'))

@issues.route('/detail/<question_id>/')
def detail(question_id):
    question = db.session.query(Question).filter(Question.id == question_id).first()
    count = db.session.query(Answer).filter(Answer.question_id == question_id).count()

    return render_template('detail.html',question = question,count=count)

@issues.route('/add_answer/', methods=['POST'])
@login_required
def add_answer():
    content = request.form.get('answer_content')
    answer = Answer(content=content)

    answer.question_id = request.form.get('question_id')
    answer.author_id = session['user_id']

    db.session.add(answer)
    db.session.commit()

    return redirect(url_for('issues.detail', question_id=answer.question_id))

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title> {% block title %}{% endblock %}--博客 </title>
  <script src="https://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
  <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{{ url_for('static',filename='css/base.css') }}">

  {% block head %}
  {% endblock %}
</head>
<body>
  <div class="row">
    <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            <div class="navbar-brand">
                <img class="logo" src="{{ url_for('static',filename='images/logo.jpeg') }}" alt="">
            </div>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">首页 <span class="sr-only">(current)</span></a></li>
            <li><a href="{{ url_for('issues.question') }}">发布问答</a></li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" name="key" value="" class="form-control" placeholder="请输入关键字">
            </div>
            <button type="submit" class="btn btn-default">查找</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
              {% if user %}
                <li><a href="#">{{ user.username }}</a></li>
                <li><a href="{{ url_for('exit') }}">注销</a></li>
              {% else %}
                  <li><a href="{{ url_for('login')}}">登入</a></li>
                <li><a href="{{ url_for('regist') }}">注册</a></li>
              {% endif %}
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>
  </div>
  <div class="main">
    {% block main %}
    {% endblock %}
  </div>
</body>
</html>

blog/templates/detail.html
{% extends 'base.html' %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/detail.css') }}">
{% endblock %}

{% block title %}详情{% endblock %}

{% block main %}
    <h3 class="page-title">{{ question.title }}</h3>
    <p class="question-info">
        <span>作者：{{ question.author.username }}</span>
        <span>时间：{{ question.create_time }}</span>
    </p>
    <hr>
    <p class="question-content">{{ question.content }}</p>
    <hr>

    <h4>评论：{{ count }}</h4>
    <form class="" action="{{ url_for('issues.add_answer',question_id = question.id ) }}" method="post">
      <div class="form-group">
          <input type="text" name="answer_content" value="" class="form-control" placeholder="评论">
          <input type="hidden" name="question_id" value="{{ question.id }}">
      </div>
      <div class="form-group" style="text-align:right">
        <button class="btn btn-primary">立即评论</button>
      </div>
    </form>

    <ul class="answer-list">
        {% for answer in question.answers %}
            <li>
                <div class="user-info">
                    <img src="{{ url_for('static',filename='images/man.png') }}" alt="" class="avatar">
                    <span class="username">{{ answer.author.username }}</span>
                    <span class="create-time">{{ answer.create_time }}</span>
                </div>
                <p class="answer-content">{{ answer.content }}</p>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

blog/templates/index.html
{% extends 'base.html' %}

{% block title %} 首页 {% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}

{% block main %}
  <ul>
    {% for question in questions %}
      <li>
        <div class="avatar-group">
            <img src="{{ url_for('static',filename='images/man.png') }}" alt="" class="avatar">
        </div>
        <div class="question-group">
            <p class="question-title"><a href="{{ url_for('issues.detail',question_id = question.id) }}">{{ question.title }}</a></p>
            <p class="question-content">{{ question.content }}</p>
            <div class="question-info">
                <span class="question-author">{{ question.author.username }}</span>
                <span class="question-time">{{ question.create_time }}</span>
            </div>
        </div>
    </li>

    {% endfor %}


  </ul>

{% endblock %}

blog/templates/login.html
{% extends 'base.html' %} {% block title %} 登入 {% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/login_regist.css') }}">
{% endblock %}
{% block main %}
    <h3 class="page-title">登录</h3>
    <form action="" method="post">
        <div class="form-container">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for msg in messages %}
                        <div class="alert alert-warning"><a href="#" class="close"
                                                            data-dismiss="alert">&times;</a>{{ msg }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <div class="form-group">
                <input type="text" name="telephone" placeholder="手机号码" class="form-control">
            </div>
            <div class="form-group">
                <input type="password" name="password" placeholder="密码" class="form-control">
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block">立即登录</button>
            </div>
        </div>
    </form>
{% endblock %}

blog/templates/question.html
{% extends 'base.html' %}
{% block title %} 登入 {% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/question.css') }}">
{% endblock %}

{% block main %}
    <h3 class="page-title">发布问答</h3>
    <form action="" method="post">
        <div class="form-container">
            <div class="form-group">
                <input type="text" name="title" placeholder="请输入标题" class="form-control">
            </div>
            <div class="form-group">
                <textarea name="content" rows="5" placeholder="请输入内容" class="form-control"></textarea>
            </div>
            <div class="form-froup">
                <button class="btn btn-primary">立即发布</button>
            </div>
        </div>
    </form>
{% endblock %}

blog/templates/regist.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/login_regist.css') }}">
{% endblock %}

{% block title %}注册{% endblock %}

{% block main %}
    <h3 class="page-title">注册</h3>
    <form action="#" method="post">
        <div class="form-container">
          {% with messages = get_flashed_messages() %}
              {% if messages %}
                  {% for msg in messages %}
                      <div class="alert alert-warning"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ msg }}
                      </div>
                  {% endfor %}
              {% endif %}
          {% endwith %}
            <div class="form-group">
                <input type="text" name="telephone" placeholder="手机号码" class="form-control">
            </div>
            <div class="form-group">
                <input type="text" name="username" placeholder="用户名" class="form-control">
            </div>
            <div class="form-group">
                <input type="password" name="password1" placeholder="密码" class="form-control">
            </div>
            <div class="form-group">
                <input type="password" name="password2" placeholder="重复密码" class="form-control">
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block">立即注册</button>
            </div>
        </div>
    </form>
{% endblock %}