PFS/feedback/models.py
from datetime import datetime
from PFS import db

class Category(db.Model):
    """分类表"""
    __tablename__ = 'category'

    ID = db.Column(db.Integer,primary_key=True)
    CategoryName = db.Column(db.String)

    def __init__(self,CategoryName):
        self.CategoryName = CategoryName

    def __repr__(self):
        return '<部门>{}:{}'.format(self.id,self.CategoryName)

class Feedback(db.Model):
    """反馈表"""
    __tablename__ = 'feedback'

    ID = db.Column(db.Integer,primary_key=True)
    Subject = db.Column(db.String)
    CategoryID = db.Column(db.Integer,db.ForeignKey('category.ID'))
    Username = db.Column(db.String)
    Email = db.Column(db.String)
    Image = db.Column(db.String)
    Body = db.Column(db.String)
    State = db.Column(db.Boolean)
    Reply = db.Column(db.String)
    ReleaseTime = db.Column(db.DateTime)

    category = db.relationship('Category',backref=db.backref('feedbacks',lazy='dynamic'))

    def __init__(self,Subject=None,Username=None,Email=None,Image=None,Body=None,State=None,Reply=None,ReleaseTime=None):
        self.Subject = Subject
        self.Username = Username
        self.Email = Email
        self.Image = Image
        self.Body = Body
        self.State = State
        self.Reply = Reply
        self.ReleaseTime = ReleaseTime if ReleaseTime else datetime.now()

    def __repr__(self):
        return '<反馈>{}'.format(self.Subject)


class User(db.Model):
    """用户信息"""
    __tablename__ = 'user'

    UserName = db.Column(db.String,primary_key=True)
    Email = db.Column(db.String)
    Password = db.Column(db.String)

    def __init__(self,UserName,Email,Password):
        self.UserName = UserName
        self.Email = Email
        self.Password = Password

    def __repr__(self):
        return '<用户:{}>'.format(self.UserName)

PFS/feedback/__init__.py
from flask import Blueprint
back = Blueprint('back',__name__)

from feedback.views import *

PFS/feedback/views.py
from datetime import datetime
from feedback import back
from flask import request,render_template,url_for,redirect,send_from_directory,session
from PFS import db
from .models import Category,Feedback
import os

UPLOAD_FOLDER = '/Users/wudaqiang/PycharmProjects/production/mysource/flask/PFS/uploads'

ALLOWED_EXTENSIONS = ['.jpg','.png','.gif']

#检查文件是否允许上传
def allowed_file(filename):
    _,ext = os.path.splitext(filename)
    #拆分扩展名，只获取后半部分ext = os.path.splitext(filename)[1]
    return ext.lower() in ALLOWED_EXTENSIONS    #返回True或False

#呈现特定目录下的资源
@back.route('/profile/<filename>/')
def render_file(filename):
    return send_from_directory(UPLOAD_FOLDER,filename)

@back.route('/feedback/')
def feedback():
    items = db.session.query(Category).all()
    return render_template('post.html',items = items)

@back.route('/post_feedback/',methods=['POST'])
def post_feedback():
    if request.method == 'POST':
        feedback = Feedback(
            Subject = request.form['subject'],
            Username = request.form.get('username'),
            Email = request.form.get('email'),
            Image = None,
            Body = request.form.get('body'),
            State = request.form.get('state',0),
            Reply = request.form.get('reply'),
            ReleaseTime = datetime.now()
        )

        if 'screenshot' in request.files:
        # if request.files['screenshot',None]:
            img = request.files['screenshot']
            if img and allowed_file(img.filename):
                img_path = datetime.now().strftime('%Y%m%d%H%M%f') + os.path.splitext(img.filename)[1]
                feedback.Image = img_path
                img.save(os.path.join(UPLOAD_FOLDER,img_path))

        feedback.CategoryID = int(request.form.get('classify'))
        db.session.add(feedback)
        db.session.commit()
        return redirect(url_for('back.feedback'))

@back.route('/admin/list/')
def feedback_list():
    if session.get('admin', None) is None:
        return redirect(url_for('admin.sign'))

    else:
        key = request.args.get('key', '')
        items = db.session.query(Feedback).filter(Feedback.Subject.contains(key)).all()
        return render_template('feedback-list.html',items=items)

@back.route('/admin/edit/<id>/')
def edit_feedback(id):
    if session.get('admin', None) is None:
        return redirect(url_for('admin.sign'))
    else:
        items = db.session.query(Category).all()
        current_feedback = db.session.query(Feedback).get(id)
        return render_template('edit.html',current_feedback = current_feedback,items=items)

@back.route('/admin/save_edit/',methods=['POST'])
def save_feedback():
    if request.method == 'POST':
        username = request.form.get('username')
        feed = db.session.query(Feedback).filter(Feedback.Username == username).first()

        feed.Subject = request.form['subject']
        feed.Username = request.form['username']
        feed.CategoryID = int(request.form.get('classify'))
        feed.Email = request.form.get('email')
        feed.Body = request.form.get('body')
        feed.State = 1 if request.form.get('state') == 'on' else 0
        feed.Reply = request.form.get('reply')
        feed.ReleaseTime = datetime.strptime(request.form.get('releasetime'),'%Y-%m-%d %H:%M:%S')
        db.session.commit()
        #图片存储的地址不用修改，所以不用写
        #request.form.get()得到的数据类型都是字符串，需用datetime.strptime()转换成datetime类型
        #查询时，filter()条件后要加.first()
    return redirect(url_for('back.feedback_list'))

@back.route('/admin/feedback/del/<id>/')
def delete_feedback(id):
    back = db.session.query(Feedback).get(id)
    db.session.delete(back)
    db.session.commit()
    return redirect(url_for('back.feedback_list'))

PFS/login/__init__.py
from flask import Blueprint

admin = Blueprint('admin',__name__)

from login.views import *

PFS/login/views.py
from flask import render_template,request,redirect,url_for,flash,session
from login import admin
from flask.views import MethodView
from PFS import db
from feedback.models import User

class Sign(MethodView):
    def get(self):
        return render_template('login.html')

    def post(self):
        username = request.form.get('username')
        pwd = request.form.get('pwd')
        count = db.session.query(User).filter(User.UserName == username).filter(User.Password == pwd).count()
        if count >0:
            session['admin'] = username
            return redirect(url_for('back.feedback_list'))
        flash("用户名或密码错误")
        return render_template('login.html')

admin.add_url_rule('/login/',view_func=Sign.as_view('sign'))

@admin.route('/exit/')
def exit():
    session.pop('admin')
    return redirect(url_for('back.feedback_list'))

PFS/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> - PFS 问题反馈系统 </title>
    <script src="https://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
    {% block head %}
    {% endblock %}
</head>
<body>
    <div class="container">
        <div class="row">
            <nav class="navbar navbar-default" role="navigation">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">PFS 问题反馈系统</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{{ url_for('back.feedback')}}">首页</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">反馈管理 <b
                                    class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('back.feedback_list')}}">问题列表</a></li>
                            </ul>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">管理员:{{session['admin'] if session['admin'] else "未登录"}} <b
                                    class="caret"></b></a>
                            <ul class="dropdown-menu">
                                {% if not session['admin'] %}
                                    <li><a href="{{ url_for('admin.sign') }}">登入</a></li>
                                {% endif %}

                                {% if session['admin'] %}
                                    <li><a href="{{ url_for('admin.exit')}}">退出</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </nav>
        </div>
        <div class="row">
            <ul class="breadcrumb">
                <li><a href="">首页</a></li>
                <li><a href="">新闻中心</a></li>
                <li class="active">新闻列表</li>
            </ul>
        </div>

        {% block main_content %}
        {% endblock %}

        <div class="row">
            <div class="well text-center">
                &copy; 版权所有 <a href="http://www.hao123.com">好123</a>
            </div>
        </div>
    </div>
</body>
</html>

PFS/templates/edit.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/edit.css') }}">
{% endblock %}

{% block main_content %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4>问题反馈 信息编辑</h4>
    </div>
    <div class="panel-body">
      <form class="form-horizontal" id="postForm" action="{{ url_for('back.save_feedback') }}" method="post">
        <div class="form-group">
          <label for="subject" class="control-label col-md-2">主题</label>
          <div class="col-md-6">
            <input type="text" class="form-control" id="subject" name="subject" value="{{ current_feedback.Subject }}">
          </div>
        </div>
        <div class="form-group">
          <label for="classify" class="control-label col-md-2">分类</label>
          <div class="col-md-2">
            <select id="classify" name="classify" class="form-control">
              {% for item in items %}
              <option {{ 'selected=selected' if item.ID == current_feedback.CategoryID }} value="{{ item.ID }}">{{ item.CategoryName }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="form-group">
          <label for="username" class="control-label col-md-2">姓名</label>
          <div class="col-md-2">
            <input type="text" class="form-control" id="username" name="username" value="{{ current_feedback.Username }}">
          </div>
        </div>
        <div class="form-group">
          <label for="email" class="control-label col-md-2">邮箱</label>
          <div class="col-md-6">
            <input type="email" class="form-control" id="email" name="email" value="{{ current_feedback.Email }}">
          </div>
        </div>
        <div class="form-group">
          <label for="image" class="control-label col-md-2">图片</label>
          <div class="col-md-2">
{#              {% if current_feedback.Image == null %}#}
                  <img src="{{ url_for('back.render_file',filename = current_feedback.Image) }}" alt="{{ current_feedback.Subject }}">
{#              {% endif %}#}

          </div>
        </div>
        <div class="form-group">
          <label for="body" class="control-label col-md-2">内容</label>
          <div class="col-md-6">
            <textarea id="body" name="body" rows="8" cols="80" class="form-control">{{ current_feedback.Body }}</textarea>
          </div>
        </div>
        <div class="form-group">
          <label for="reply" class="control-label col-md-2">回复</label>
          <div class="col-md-6">
            <textarea id="reply" name="reply" rows="8" cols="80" class="form-control">{{ current_feedback.Reply if current_feedback.Reply }}</textarea>
          </div>
        </div>
        <div class="form-group">
          <label for="state" class="control-label col-md-2">处理</label>
          <div class="col-md-6">
            <input type="checkbox" id="state" name="state" {{ 'checked=checked' if current_feedback.State == 1 }}>
          </div>
        </div>
        <div class="form-group">
          <label for="releasetime" class="control-label col-md-2">发布时间</label>
          <div class="col-md-6">
            <input type="text" name="releasetime" id="releasetime" class="form-control" value="{{ current_feedback.ReleaseTime.strftime('%Y-%m-%d %H:%M:%S')}}">
          </div>
        </div>
        <div class="form-group">
          <label for="" class="control-label col-md-2"></label>
          <div class="col-md-6">
            <input type="submit" class="btn btn-primary" value="提交">
            <input type="reset" class="btn btn-default" value="重置">
            <a href="{{ url_for('back.feedback_list') }}" class="btn btn-default" >返回列表</a>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

PFS/templates/feedback-list.html
{% extends "base.html" %} {% block main_content %}
<div class="row">
  <div class="panel panel-default">
    <div class="panel-heading">
      <form class="form-inline" action="#">
        <input type="text" name="key" id="key" value="{{ request.args.get('key') if request.args.get('key') }}" class="form-control">
        {# value="{{ request.args.get('key') 为了保留搜索的文字#}
        <input type="submit" class="btn btn-default" value="搜索">
      </form>
    </div>
    <div class="panel-body">
      <table class="table table-hover">
        <tr>
          <th>#</th>
          <th>主题</th>
          <th>分类</th>
          <th>用户</th>
          <th>邮箱</th>
          <th>处理状态</th>
          <th>提交时间</th>
          <th>操作</th>
        </tr>
        {% for item in items %}
        <tr>
          <td>{{ loop.index }}</td>
          <td>{{ item.Subject }}</td>
          <td>{{ '产品质量' if item.CategoryID == 1 else '客户服务' if item.CategoryID == 2 else '购买支付' }}</td>
          <td>{{ item.Username }}</td>
          <td>{{ item.Email }}</td>
          <td><span class="label label-{{'danger' if item.State == 0 else 'success' }}">{{ '待处理' if item.State == 0 else '已处理' }}</span></td>
          <td>{{ item.ReleaseTime.strftime('%Y-%m-%d %H:%M:%S') }}</td>
          <td>
            <a href="#" class="btn btn-default btn-xs" title="查看"><i class="fa fa-search"></i></a>
            <a href="{{ url_for('back.edit_feedback',id=item.ID)}}" class="btn btn-default btn-xs" title="编辑"><i class="fa fa-pencil"></i></a>
            <a href="{{ url_for('back.delete_feedback',id = item.ID) }}" class="btn btn-default btn-xs" title="删除"><i class="fa fa-trash"></i></a>
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</div>
{% endblock %}

PFS/templates/login.html
{% extends 'base.html' %}
{% block main_content %}
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">管理员登入</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <form action="/login/" autocomplete="off" method="post">
              {% with messages = get_flashed_messages() %}
{#                  得到的不是字符串而是集合#}
                {% if messages %}
                  {% for msg in messages %}
                    <div class="alert alert-warning"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ msg }}</div>
                  {% endfor %}
                {% endif %}
              {% endwith %}
              <div class="form-group">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-user"></i></span>
                  <input type="text" id="username" name="username" placeholder="用户名" class="form-control">
                </div>
              </div>
              <div class="form-group">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                  <input type="password" id="pwd" name="pwd" placeholder="密码" class="form-control">
                </div>
              </div>
              <div class="pull-right">
                <input type="submit" name="" value="登录" class="btn btn-primary">
                <a href="#" class="btn btn-default">返回首页</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

PFS/templates/post.html
{% extends 'base.html' %}

{% block main_content %}
    <div class="row">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>问题反馈</h4>
        </div>
        <div class="panel-body">
          <form class="form-horizontal" enctype="multipart/form-data" id="postForm" action="{{ url_for('back.post_feedback')}}" method="post">
            <div class="form-group">
              <label for="subject" class="control-label col-md-2">主题</label>
              <div class="col-md-6">
                <input type="text" class="form-control" id="subject" name="subject">
              </div>
            </div>
            <div class="form-group">
              <label for="classify" class="control-label col-md-2">分类</label>
              <div class="col-md-2">
                <select id="classify" name="classify" class="form-control">
                  {% for item in items %}
                  <option value="{{ item.ID }}">{{ item.CategoryName }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <div class="form-group">
              <label for="username" class="control-label col-md-2">姓名</label>
              <div class="col-md-2">
                <input type="text" class="form-control" id="username" name="username">
              </div>
            </div>
            <div class="form-group">
              <label for="email" class="control-label col-md-2">邮箱</label>
              <div class="col-md-6">
                <input type="email" class="form-control" id="email" name="email">
              </div>
            </div>
            <div class="form-group">
              <label for="screenshot" class="control-label col-md-2">图片</label>
              <div class="col-md-2">
                <input type="file" id="screenshot" name="screenshot">
              </div>
            </div>
            <div class="form-group">
              <label for="body" class="control-label col-md-2">内容</label>
              <div class="col-md-6">
                <textarea id="body" name="body" rows="8" cols="80" class="form-control"></textarea>
              </div>
            </div>
            <div class="form-group">
              <label for="" class="control-label col-md-2"></label>
              <div class="col-md-6">
                <input type="submit" class="btn btn-primary" value="提交">
                <input type="reset" class="btn btn-default" value="重置">
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
{% endblock %}